### ISSUE TITLE
Error after activating theme

### ISSUE THREAD

**Issue by adamtbeames** [doubleedesign/Double-E-Foundation#1]
After installing and activating theme I'm unable to load the site anymore.  Site only shows a spinning circle.  

I found the following error in the apache logs:
`[Tue Mar 03 23:59:20.993797 2020] [php7:error] [pid 31535] [client X.X.X.X:61977] PHP Fatal error:  Uncaught Error: Call to undefined function get_field() in /var/www/html/wordpress/wp-content/themes/Double-E-Foundation/header.php:48\nStack trace:\n#0 /var/www/html/wordpress/wp-includes/template.php(722): require_once()\n#1 /var/www/html/wordpress/wp-includes/template.php(671): load_template('/var/www/html/w...', true)\n#2 /var/www/html/wordpress/wp-includes/general-template.php(41): locate_template(Array, true)\n#3 /var/www/html/wordpress/wp-content/themes/Double-E-Foundation/page.php(14): get_header()\n#4 /var/www/html/wordpress/wp-includes/template-loader.php(98): include('/var/www/html/w...')\n#5 /var/www/html/wordpress/wp-blog-header.php(19): require_once('/var/www/html/w...')\n#6 /var/www/html/wordpress/index.php(17): require('/var/www/html/w...')\n#7 {main}\n  thrown in /var/www/html/wordpress/wp-content/themes/Double-E-Foundation/header.php on line 48, referer: https://www.example.org/wp-admin/themes.php`

**Comment by doubleedesign** [comment]
Hey Adam, thanks for trying out my theme! It's designed to work with the Advanced Custom Fields plugin, so that error occurs if you don't have it installed.  If you install and activate that plugin you shouldn't get that error anymore :)

**Comment by adamtbeames** [comment]
Thanks Leesa.  Will see how I go.

**Comment by doubleedesign** [comment]
I've updated the readme to list it as required rather than recommended, noting that the code that uses it can be removed if desired. Let me know if you have any other feedback or run into any other issues  :)

**Comment by adamtbeames** [comment]
No more errors :)
Now I need to work out how to use it.
I like the layout of some of your other sites which is why I thought this could be a good starting point. Thanks!
